events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location = / {
      try_files /index.html =404;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }

    location /api/users/ {
      proxy_pass http://user_service:8000/api/;
    }

    location /api/products/ {
      proxy_pass http://product_service:8000/api/products/;
    }

    location /api/orders/ {
      proxy_pass http://order_service:8000/api/;
    }

    location /api/behavior/recommend/ {
      proxy_pass http://behavior_service:8000/api/recommend/;
    }

    location /api/chat/ {
      proxy_pass http://rag_chat_service:8000/api/chat/;
    }
  }
}
