# Generated by Django 4.2.7 on 2026-04-15

from django.db import migrations


PRODUCT_SEEDS = [
    {
        "name": "Sony WH-1000XM5",
        "category": "Audio",
        "price": "8990000",
        "ai_match": 95,
        "image_icon": "headphones",
    },
    {
        "name": "Keychron Q1",
        "category": "Accessories",
        "price": "4290000",
        "ai_match": 91,
        "image_icon": "keyboard",
    },
    {
        "name": "Logitech MX Master 3S",
        "category": "Accessories",
        "price": "2490000",
        "ai_match": 93,
        "image_icon": "mouse",
    },
    {
        "name": "LG UltraGear 27",
        "category": "Monitor",
        "price": "6790000",
        "ai_match": 88,
        "image_icon": "monitor",
    },
    {
        "name": "Dell XPS 13",
        "category": "Laptop",
        "price": "32990000",
        "ai_match": 90,
        "image_icon": "laptop",
    },
    {
        "name": "MacBook Air M3",
        "category": "Laptop",
        "price": "28990000",
        "ai_match": 94,
        "image_icon": "laptop",
    },
    {
        "name": "Anker 737 Power Bank",
        "category": "Accessories",
        "price": "3190000",
        "ai_match": 84,
        "image_icon": "battery",
    },
    {
        "name": "Samsung T7 Shield 1TB",
        "category": "Storage",
        "price": "2590000",
        "ai_match": 86,
        "image_icon": "drive",
    },
    {
        "name": "JBL Flip 6",
        "category": "Audio",
        "price": "2590000",
        "ai_match": 82,
        "image_icon": "speaker",
    },
    {
        "name": "Rain Design mStand",
        "category": "Accessories",
        "price": "1590000",
        "ai_match": 80,
        "image_icon": "stand",
    },
]


def seed_products(apps, schema_editor):
    Product = apps.get_model("api", "Product")

    for product in PRODUCT_SEEDS:
        Product.objects.get_or_create(
            name=product["name"],
            defaults=product,
        )


def unseed_products(apps, schema_editor):
    Product = apps.get_model("api", "Product")
    product_names = [product["name"] for product in PRODUCT_SEEDS]
    Product.objects.filter(name__in=product_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_products, unseed_products),
    ]
