# Generated by Django 6.0.3 on 2026-04-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.CharField(default='0.00', max_length=50),
        ),
    ]
