# Generated by Django 4.2.7 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_number", models.CharField(max_length=50)),
                ("carrier", models.CharField(max_length=100)),
                ("tracking_number", models.CharField(max_length=100, unique=True)),
                ("shipping_status", models.CharField(default="pending", max_length=50)),
                ("destination", models.CharField(max_length=255)),
                ("eta_days", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
